export interface User { id: string; username: string; email: string; full_name: string; role: string; }
export interface DashboardData { total_roles: number; total_users: number; total_permissions: number; excessive_permissions: number; unused_permissions: number; high_risk_permissions: number; policies_analyzed: number; permissions_removed: number; risk_reduction: number; simulation_pass_rate: number; permissions_by_risk: {name: string; value: number; color: string}[]; permissions_used_vs_unused: {used: number; unused: number}; risk_reduction_over_time: {date: string; score: number}[]; roles_by_security_score: {name: string; score: number; risk_level: string}[]; }
export interface IAMRole { id: string; role_name: string; service: string; total_permissions: number; used_permissions: number; unused_permissions: number; risk_score: number; risk_level: string; last_activity: string; status: string; arn?: string; description?: string; excessive_permissions?: number; }
export interface Permission { id: string; action: string; resource: string; effect: string; service: string; is_wildcard: boolean; is_admin: boolean; risk_level: string; is_used: boolean; usage_count: number; last_used: string | null; required_by: string | null; recommendation: string; description: string; }
export interface AccessLog { id: string; action: string; resource: string; timestamp: string; source_ip: string; status: string; region: string; role_name: string; }
export interface Candidate { id: string; action: string; resource: string; reason: string; risk_level: string; recommendation: string; confidence: number; evidence: any; status: string; role_name: string; role_id: string; }
export interface PolicyCompare { current_policy: any; proposed_policy: any; changes: PolicyChange[]; explanation: string; }
export interface PolicyChange { action: string; change_type: string; reason: string; confidence: number; }
export interface SimulationResult { test_action: string; test_resource: string; original_result: string; proposed_result: string; status: string; reason: string; affected_service: string | null; }
export interface SimulationResponse { passed: boolean; results: SimulationResult[]; iteration: number; summary: string; }
export interface VerificationCheck { name: string; passed: boolean; description: string; }
export interface VerificationResponse { checks: VerificationCheck[]; score_before: number; score_after: number; risk_reduction: number; }
export interface AuditLogEntry { id: string; event_type: string; action: string; permission_action: string | null; role_name: string | null; reason: string | null; evidence: string | null; confidence: number | null; simulation_status: string | null; timestamp: string; details: any; }
export interface AnalysisRun { id: string; status: string; current_state: string; started_at: string; completed_at: string | null; total_permissions_analyzed: number; excessive_found: number; unused_found: number; candidates_generated: number; permissions_removed: number; permissions_retained: number; simulation_iterations: number; risk_reduction: number; initial_score: number; final_score: number; error_message: string | null; }
export interface ServiceDependency { source_service: string; target_service: string; dependency_type: string; required_permissions: string[]; description: string; is_critical: boolean; }
export interface ReportData { executive_summary: string; run: AnalysisRun; roles_analyzed: IAMRole[]; candidates: Candidate[]; policy_changes: PolicyChange[]; simulation_results: SimulationResult[]; verification: VerificationResponse; audit_trail: AuditLogEntry[]; }
